### ISSUE TITLE
Add FirefoxColor repo

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-pm#423]
Can https://github.com/mozilla/FirefoxColor be added to the dashboard?

**Comment by muffinresearch** [comment]
Presumably you're asking for this to be added to the contrib dashboard?

**Comment by Rob--W** [comment]
Yep. I added contrib labels yesterday following the gfb meeting.

**Comment by muffinresearch** [comment]
This is fixed and released 👍

**Comment by Rob--W** [comment]
Thanks. It was done in #431 / https://github.com/mozilla/addons-pm/commit/152a6fbf1478bdd17448ccfdab1d100b1d138407
