### ISSUE TITLE
"ux" list is wrong on webext dashboard

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/addons-pm#424]
@muffinresearch  I created a new list https://bugzilla.mozilla.org/buglist.cgi?cmdtype=runnamed&namedcmd=addons-ux&list_id=15484015

**Comment by muffinresearch** [comment]
That link doesn't work for me. 

Can you explain how the UX list is wrong? I'd need to use a API call to get the data. The link should then be created from all of the ids related to that call.

**Comment by mixedpuppy** [comment]
do a search with addons-ux in the whiteboard.  I guess that + email addresses would be better.

**Comment by muffinresearch** [comment]
This is fixed in the Next.js version which has now landed and been released. That uses the whiteboard tag.
