### ISSUE TITLE
Add web-ext and webextensions-polyfill good-first-bugs to Contributions? 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-pm#98]
Could we add [web-ext good-first-bugs](https://github.com/mozilla/web-ext/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22) to the Contributions panel of the Addons PM for greater visibility?

**Comment by muffinresearch** [comment]
Yep definitely. I should be able to get that done before the next call.

**Comment by rpl** [comment]
@muffinresearch @caitmuenster we may add also the polyfill repo as well ([webextensions-polyfill good-first-bugs](https://github.com/mozilla/webextension-polyfill/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22))
